name: Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run tests
      run: uv run pytest tests/ -v --tb=short
    
    - name: Test CLI commands
      run: |
        uv run python -m ai_secrets --help
        uv run python -m ai_secrets --service-name ci-test set TEST_KEY "test_value"
        uv run python -m ai_secrets --service-name ci-test get TEST_KEY --reveal -f json
        uv run python -m ai_secrets --service-name ci-test list -f json
        uv run python -m ai_secrets --service-name ci-test delete TEST_KEY --yes

